import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9ff',
    padding: 16,
  },
  formContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 15,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  entriesContainer: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4338ca',
    marginBottom: 16,
    textShadowColor: 'rgba(99, 102, 241, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    backgroundColor: 'white',
    padding: 14,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
    fontSize: 16,
    color: '#1e1b4b',
    shadowColor: '#a5b4fc',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  button: {
    backgroundColor: '#4f46e5',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  entryCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#a5b4fc',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.1)',
  },
  entryDate: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4338ca',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  entryDetails: {
    marginBottom: 12,
    backgroundColor: 'rgba(224, 231, 255, 0.2)',
    padding: 12,
    borderRadius: 8,
  },
  detailText: {
    fontSize: 16,
    color: '#1e1b4b',
    marginBottom: 6,
  },
  consumption: {
    color: '#4f46e5',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 8,
    backgroundColor: 'rgba(224, 231, 255, 0.4)',
    padding: 8,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  notes: {
    color: '#6b7280',
    fontStyle: 'italic',
    backgroundColor: 'rgba(243, 244, 246, 0.5)',
    padding: 8,
    borderRadius: 6,
    marginTop: 8,
  },
}); 