import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9ff',
  },
  formContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 15,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4338ca',
    marginBottom: 16,
    textShadowColor: 'rgba(99, 102, 241, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    backgroundColor: 'white',
    padding: 14,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
    fontSize: 16,
    color: '#1e1b4b',
  },
  button: {
    backgroundColor: '#4f46e5',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  maintenanceContainer: {
    padding: 20,
  },
  maintenanceCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#a5b4fc',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.1)',
  },
  maintenanceDate: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4338ca',
    marginBottom: 12,
  },
  maintenanceDetails: {
    marginBottom: 12,
  },
  maintenanceType: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  detailText: {
    fontSize: 16,
    color: '#1e1b4b',
  },
  nextDue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#10b981',
  },
  notes: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#666',
  },
  buttonContainer: {
    marginTop: 10,
    alignItems: 'flex-end',
    paddingRight: 10,
  },
  markDoneButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  markDoneButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  completedTitle: {
    color: '#666',
    marginTop: 20,
  },
  completedCard: {
    opacity: 0.6,
    backgroundColor: '#f5f5f5',
    borderColor: 'rgba(99, 102, 241, 0.05)',
  },
  completedText: {
    color: '#666',
  },
}); 